import './globals.css'
import ClientOnly from './components/ClientOnly'
import LoginModal from './components/modals/LoginModal'
import RegisterModal from './components/modals/RegisterModal'
import Navbar from './components/navbar/Navbar'
import { Nunito } from 'next/font/google'
import ToasterProvider from './providers/ToasterProvider'
import AuthProvider from './providers/AuthProvider'
import getCurrentUser from './actions/getCurrentUser'
import RentModal from './components/modals/RentModal'
import Footer from "@/app/(site)/components/Footer/Footer"

export const metadata = {
  title: 'AirBnb',
  description: 'Generated by ME',
}


const font = Nunito({
  subsets:['latin']
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  
  return (
    <html lang="en">
      <body className={font.className}>
          <AuthProvider>
        <ClientOnly>
            <ToasterProvider/>
            <RegisterModal/>
            <LoginModal/>
            <RentModal/>
        </ClientOnly>
        <div className="pb-20 pt-0">
          {children}
        </div>
          </AuthProvider>
      </body>
    </html>
  )
}
